title: tinyc.games
description: Tiny C games you can compile and run RIGHT NOW
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

github:
  zip_url: https://github.com/superjer/tinyc.games/archive/master.zip
  tar_url: https://github.com/superjer/tinyc.games/archive/master.tar.gz
